### ISSUE TITLE
Keyword arguments should follow non-keyword arguments.

### ISSUE THREAD

**Issue by randdane** [ekozlowski/simpleMail#4]
_send_message(message='testMsg', 'This is a test... this is only a test.')_
should be: 
_send_message('This is a test... this is only a test.', message='testMsg')_

I only found this because I was using Python 3.

**Comment by ekozlowski** [comment]
Awesome, thanks!  I'll get this fixed right away.

**Comment by ekozlowski** [comment]
This was fixed, and I added native support for Python 3 now, so you don't have to work around the imports.  :)

**Comment by randdane** [comment]
Happy to help. Still trying to wrap my head around how this stuff works.
